version: '3'
services:
  # Elixir/Phoenix API
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
  # PostgreSQL Database
  database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    volumes:
       - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_USER=root
  # Nginx Reverse Proxy
  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - '80:80'
  # React Client
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/public:/usr/local/apache2/htdocs/

