version: '3'
services:
  ### Elixir/Phoenix API (dev / prod)
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  ### PostgreSQL Database
  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    volumes:
       - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_USER=chestnut
      - PGDATA=/var/lib/postgresql/data/pgdata # https://stackoverflow.com/questions/35679995/how-to-use-postgresql-container-with-existing-data
  # Nginx Reverse Proxy
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./nginx/Dockerfile
  #   ports:
  #     - '80:80'
  ### React Client for Developement
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/chestnut_client:/app
  ### Production build of React Client
  # public:
  #   image: httpd
  #   volumes:
  #     - ./frontend/public:/usr/local/apache2/htdocs/
